version: "3"
services:
  ui:
    build:
      dockerfile: "Dockerfile"
      context: "."
    volumes:
      - ./build:/usr/local/lib/build
    networks:
      - infraserver
networks:
    infraserver:
